project:
  type: book
  output-dir: docs
book:
  title: "Statistical Methods for Composite Endpoints"
  subtitle: "Win Ratio and Beyond"
  author: "Lu Mao"
  twitter-card: true
  # date: "5/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - testing.qmd
    - estimation.qmd
    - regression.qmd
    - discussions.qmd
    - references.qmd



# about: 
#   template: jolla
#   links:
#     - icon: twitter
#       text: Twitter
#       href: https://x.com/LuMaoWisc
#     - icon: linkedin
#       text: LinkedIn
#       href: https://www.linkedin.com/in/lu-mao-63589b14/
#     - icon: github
#       text: Github
#       href: https://github.com/lmaowisc

bibliography: references.bib
csl: apa.csl
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

